---
# proxychains config
proxychains_config_path: /etc/proxychains.conf
strict_chain_regexp: '^strict_chain'
strict_chain_line: '#strict_chain'
dynamic_chain_regexp: '^#dynamic_chain'
dynamic_chain_line: 'dynamic_chain'
socks_regexp: '^socks4'
socks_line: 'socks5 127.0.0.1 9050'

# rockyou path
rockyou_path: /usr/share/wordlists/rockyou.txt.gz