---
- name: Configuration for a fresh kali image
  hosts: localhost
  connection: local
  vars_files:
    - ./defaults/firefox.yml

  roles:
    - desktop
    - terminal
    - apps
    - basvandenbrink.firefox
