---
- name: Set greeter background
  ansible.builtin.lineinfile:
    path: '{{ greeter_config_path }}'
    regexp: '{{ greeter_bg_regexp }}'
    line: '{{ greeter_bg_line }}'
  become: yes

- name: Hide greeter user image
  ansible.builtin.lineinfile:
    path: '{{ greeter_config_path }}'
    line: '{{ greeter_hide_user_image_line }}'
    insertbefore: EOF
  become: yes

- name: Set keyboard shortcuts
  ansible.builtin.lineinfile:
    path: '{{ xfce_config_path }}{{ keyboard_config_file }}'
    regexp: '{{ keyboard_close_key_regexp }}'
    line: '{{ keyboard_close_key_line }}'

- name: Set launcher config
  ansible.builtin.template:
    src: '{{ launcher_config_file }}'
    dest: '{{ xfce_config_path }}'
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: 0644

- name: Set launcher panel directories
  file:
    state: directory
    dest: '{{ xfce_panel_config_path }}/{{ item.path }}'
  with_filetree: '../templates/launcher'
  when: item.state == 'directory'

- name: Set launcher panel files
  template:
    src: '{{ item.src }}'
    dest: '{{ xfce_panel_config_path }}/{{ item.path }}'
  with_filetree: '../templates/launcher'
  when: item.state == 'file'

- name: Refresh panel
  command: xfce4-panel -r

- name: Set desktop config
  copy: src={{ desktop_config_file }} dest={{ xfce_config_path }}

- name: Refresh desktop
  shell: |
    killall xfconfd
    /usr/lib/x86_64-linux-gnu/xfce4/xfconf/xfconfd &
    killall xfdesktop