---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become: yes

- name: Install additional packages
  apt:
    pkg:
    - torbrowser-launcher
    - rlwrap
    - exiftool
  become: yes