---
# greeter config
greeter_config_path: /etc/lightdm/lightdm-gtk-greeter.conf
greeter_bg_regexp: '^background(.*)$'
greeter_bg_line: 'background = #161616'
greeter_hide_user_image_line: 'hide-user-image = true'

# xfce config
xfce_config_path: ~/.config/xfce4/xfconf/xfce-perchannel-xml/
xfce_panel_config_path: ~/.config/xfce4/panel/
keyboard_config_file: xfce4-keyboard-shortcuts.xml
launcher_config_file: xfce4-panel.xml
desktop_config_file: xfce4-desktop.xml

# keyboard shortcuts
keyboard_close_key_regexp: '^(.*)close_window_key(.*)'
keyboard_close_key_line: '<property name="&lt;Primary&gt;q" type="string" value="close_window_key"/>'