---
- name: Install Tor Browser
  ansible.builtin.package:
    name: torbrowser-launcher
    state: present
  become: yes

- name: Unarchive rockyou wordlist
  command: gzip -d {{ rockyou_path }}
  become: yes
  ignore_errors: yes