---
- name: Customize greeter
  copy: src=lightdm-gtk-greeter.conf dest=/etc/lightdm/
  become: yes

- name: Customize desktop
  copy: src=xfce4-desktop.xml dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/

- name: Refresh desktop
  shell: |
    killall xfconfd
    /usr/lib/x86_64-linux-gnu/xfce4/xfconf/xfconfd &
    killall xfdesktop
