---
- name: Set greeter background
  ansible.builtin.lineinfile:
    path: '{{ greeter_config_path }}'
    regexp: '{{ greeter_bg_regexp }}'
    line: '{{ greeter_bg_line }}'
  become: yes

- name: Hide greeter user image
  ansible.builtin.lineinfile:
    path: '{{ greeter_config_path }}'
    line: '{{ greeter_hide_user_image_line }}'
    insertbefore: EOF
  become: yes

- name: Set keyboard shortcuts
  ansible.builtin.lineinfile:
    path: '{{ keyboard_config_path }}'
    regexp: '{{ keyboard_close_key_regexp }}'
    line: '{{ keyboard_close_key_line }}'

- name: Set launcher config
  ansible.builtin.template:
    src: '{{ launcher_config_file }}'
    dest: '{{ launcher_config_path }}'
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: 0644

# @TODO add launcher shortcuts

- name: Set desktop config
  copy: src={{ desktop_config_file }} dest={{ desktop_config_path }}

- name: Refresh desktop
  shell: |
    killall xfconfd
    /usr/lib/x86_64-linux-gnu/xfce4/xfconf/xfconfd &
    killall xfdesktop
